<div data-role="content-wrapper" id="footer">
  <a href="{{ view.company.homepage }}"><img class="footer-logo" src="{{ view.company.logoPath }}"/></a>

  <p>Neat is maintained and funded by <a href="{{ view.company.homepage }}">{{ view.company.name }}</a>.</p>
  <p>Documentation generated using <a href="http://sassdoc.com/">SassDoc</a>.</p>
  <p>The names and logos are trademarks of {{ view.company.name }} © <span id="year">{{ view.company.trademarkYears }}</span></p>
</div>
