<div data-role="content-wrapper" id="footer">
  <a href="http://thoughtbot.com"><img class="footer-logo" src="https://raw.githubusercontent.com/thoughtbot/presskit/master/logo/circle/png/robot_only_default.png"/></a>

  <p>Neat is maintained and funded by <a href="http://thoughtbot.com/">thoughtbot</a>.</p>
  <p>Documentation generated using <a href="http://sassdoc.com/">SassDoc</a>.</p>
  <p>The names and logos for thoughtbot are trademarks of thoughtbot, inc. © <span id="year">2012-2015</span></p>
</div>
